name: Manual Deploy to AWS EC2

on:
  workflow_dispatch:   # ðŸ‘ˆ manual trigger button

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy Code to AWS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Code to AWS EC2
        run: |
          ssh ubuntu@${{ secrets.AWS_HOST }} << 'EOF'
            cd /home/ubuntu/interest_pay

            echo "Pulling latest code..."
            git pull origin main

            echo "Stopping old containers..."
            docker-compose down

            echo "Cleaning old images..."
            docker system prune -af

            echo "Freeing port 5000..."
            sudo lsof -ti :5000 | xargs -r sudo kill -9

            echo "Rebuilding & starting containers..."
            docker-compose up -d --build

            echo "Deployment completed successfully!"
          EOF
