name: Deploy to Contabo VPS Frontend (Manual)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment environment"
        required: true
        default: "production"
      branch:
        description: "Branch to deploy"
        required: true
        default: "main"
      directory:
        description: "Directory to be deploy in"
        required: true
        default: "frontend"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout selected branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.CONTABO_SSH_KEY }}

      - name: Deploy to Contabo
        run: |
          ssh -tt -o StrictHostKeyChecking=no \
          ${{ secrets.CONTABO_USER }}@${{ secrets.CONTABO_HOST }} \
          "export NVM_DIR=\$HOME/.nvm && \
           [ -s \"\$NVM_DIR/nvm.sh\" ] && . \"\$NVM_DIR/nvm.sh\" && \
           nvm install 20 && \
           nvm use 20 && \
           node -v && npm -v && \
           cd /home/ubuntu/${{ github.event.inputs.directory }} && \
           git fetch origin && \
           git checkout ${{ github.event.inputs.branch }} && \
           git pull origin ${{ github.event.inputs.branch }} && \
           npm install && \
           npm run build && \
           pm2 restart all"
