name: Deploy to AWS EC2

on:
  push:
    branches: [ "main" ]  # Deploy only when pushing to feat/auth

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy Code to AWS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > aws_key.pem
          chmod 600 aws_key.pem

      - name: Deploy Code to AWS EC2
        run: |
          ssh ubuntu@${{ secrets.AWS_HOST }} << 'EOF'
            cd /home/ubuntu/interest_pay
            git pull origin main
            docker compose down
            docker compose up -d --build
          EOF

