name: Deploy to AWS EC2

on:
  push:
    branches: [ "main" ]  # Deploy only when pushing to feat/auth

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy Code to AWS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > aws_key.pem
          chmod 600 aws_key.pem

      - name: Deploy Code to AWS EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i aws_key.pem ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} << 'EOF'
            cd /interestPe  # Change this to your actual project directory
            git pull origin main  # Pull latest code from GitHub
            npm install  
            systemctl restart myapp 
          EOF
